apiVersion: v1
kind: Service
metadata:
  name: inventory-service-node
  labels:
    app: inventory-service-node
spec:
  type: NodePort
  selector:
    app: inventory-service-node
  ports:
    - protocol: TCP
      port: 3013
      targetPort: 3013